#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
事件常量模块

定义了应用程序中使用的所有事件常量
"""

# UI事件
LOAD_PHBOM_CLICKED = "LOAD_PHBOM_CLICKED"
CLEAR_MOD_CLICKED = "CLEAR_MOD_CLICKED"
GENERATE_CLICKED = "GENERATE_CLICKED"
CHECK_CLICKED = "CHECK_CLICKED"

# 配置文件相关事件
CONFIG_FILE_SELECT_CLICKED = "CONFIG_FILE_SELECT_CLICKED"
CONFIG_FILE_OK_CLICKED = "CONFIG_FILE_OK_CLICKED"
CONFIG_FILE_SELECTED = "CONFIG_FILE_SELECTED"
CONFIG_FILE_LOADED = "CONFIG_FILE_LOADED"

# 工作表相关事件
SHEET_SELECTED = "SHEET_SELECTED"
SHEET_LIST_UPDATED = "SHEET_LIST_UPDATED"
SHEET_CHANGED = "SHEET_CHANGED"

# P/N相关事件
PN_SELECTED = "PN_SELECTED"
PN_LIST_UPDATED = "PN_LIST_UPDATED"
PN_CHANGED = "PN_CHANGED"

# 配置详情相关事件
CONFIG_DETAILS_UPDATED = "CONFIG_DETAILS_UPDATED"

# PHBOM相关事件
PHBOM_FILE_SELECTED = "PHBOM_FILE_SELECTED"
PHBOM_FILE_LOADED = "PHBOM_FILE_LOADED"
PHBOM_DATA_UPDATED = "PHBOM_DATA_UPDATED"

# OS MOD相关事件
OS_MOD_OPTIONS_UPDATED = "OS_MOD_OPTIONS_UPDATED"
OS_MOD_SELECTED = "OS_MOD_SELECTED"
OS_MOD_CHANGED = "OS_MOD_CHANGED"
OS_MOD_ADD_CLICKED = "OS_MOD_ADD_CLICKED"
BYPASS_WHQL_CLICKED = "bypass_whql_clicked"

# MOD相关事件
MOD_LOAD_CLICKED = "MOD_LOAD_CLICKED"
MOD_ADD_CLICKED = "MOD_ADD_CLICKED"

# 关键部件相关事件
KEYPARTS_LOAD_CLICKED = "KEYPARTS_LOAD_CLICKED"
KEYPARTS_SEARCH_CLICKED = "KEYPARTS_SEARCH_CLICKED"
KEYPARTS_ADD_CLICKED = "KEYPARTS_ADD_CLICKED"
KEYPARTS_CLEAR_CLICKED = "KEYPARTS_CLEAR_CLICKED"

# APP MOD相关事件
APP_MOD_ADD_CLICKED = "APP_MOD_ADD_CLICKED"

# 错误事件
ERROR_OCCURRED = "ERROR_OCCURRED"

# 系统事件
STATUS_UPDATED = "STATUS_UPDATED"

# 新增确保所有事件类型常量都在这里定义
"""
事件常量模块

这个模块定义了应用程序中使用的所有事件名称，
确保事件名称的一致性和可维护性。
"""

# 文件相关事件
FILE_SELECTED = "file_selected"

# 模块面板事件
WHQL_CHANGED = "WHQL_CHANGED"

# 模型事件
PHBOM_DATA_PROCESSED = "phbom_data_processed"

# 配置文件相关事件
CONFIG_FILE_SELECT_CLICKED = "config_file_select_clicked"
CONFIG_FILE_OK_CLICKED = "config_file_ok_clicked"
CONFIG_FILE_SELECTED = "config_file_selected"

# 工作表相关事件
SHEET_SELECTED = "sheet_selected"

# P/N相关事件
PN_SELECTED = "pn_selected"

# 配置详情相关事件
CONFIG_DETAILS_UPDATED = "config_details_updated"

# PHBOM相关事件
PHBOM_FILE_SELECTED = "phbom_file_selected"

# OS MOD相关事件
OS_MOD_OPTIONS_UPDATED = "os_mod_options_updated"
OS_MOD_SELECTED = "os_mod_selected"

# 错误相关事件
ERROR_OCCURRED = "error_occurred" 